### ISSUE TITLE
Show only nodes of predefined domains

### ISSUE THREAD

**Issue by citronalco** [freifunk/meshviewer#105]
## Is your feature request related to a problem? Please describe.

We are in charge for the Freifunk networks of two cities. Each city has its own domain and its own public website.
We would like to run a Meshviewer instance for each of the domains, only showing the domain's nodes, using a common (global) meshviewer.json.

## Describe the solution you'd like

Add a config option, e.g. "domainFilter", where one can give one or more domain names. Nodes from domains not listed get ignored.

## Describe alternatives you've considered

Alternatively we would have to run several Yanic instances, or create filters for each domain that read meshviewer.json, removes all nodes not belonging to the desired domain, and feeds the result to Meshviewer.

**Comment by herbetom** [comment]
I think filtering via yanic is the way to go. It's not necessary to run several instances. Just define multiple filtered outputs:

```toml

# Community A

[[nodes.output.meshviewer-ffrgb]]
enable   = true
path = "/srv/yanic/comA/meshviewer.json"

[nodes.output.meshviewer-ffrgb.filter]
domain_as_site = true
sites = ["dom1", "dom2"]


# Community B

[[nodes.output.meshviewer-ffrgb]]
enable = true
path = "/srv/yanic/comB/meshviewer.json"

[nodes.output.meshviewer-ffrgb.filter]
domain_as_site = true
sites = ["dom3"]

```

---

FFMUC did just that and it seems to work for them:

https://github.com/freifunkMUC/ffmuc-salt-public/pull/151
https://github.com/freifunkMUC/ffmuc-salt-public/pull/152
